name: Liquidator CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
