name: Liquidator CI

on:
  push:
    paths:
      - "liquidator/**"
      - ".github/workflows/liquidator.yml"
  pull_request:
    paths:
      - "liquidator/**"
      - ".github/workflows/liquidator.yml"

jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./liquidator
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
